services:
  frontend:
    build:
      context: ./cybershield-react
      dockerfile: Dockerfile
    container_name: cybershield-frontend  
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./cybershield-react/build:/usr/share/nginx/html
      - ./cybershield-react/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./ssl:/etc/nginx/ssl  # Map your existing SSL directory
      - ./ssl/server.crt.real:/etc/nginx/ssl/server.crt  # Override with real cert
      - ./ssl/server.key.real:/etc/nginx/ssl/server.key  # Override with real key

    depends_on:
      - backend
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=443
    restart: unless-stopped  
    networks:
      - cybershield-network
    
    
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      mongodb:
        condition: service_healthy
    environment:
      - MONGO_URI=mongodb://mongodb:27017/cybershield_db
      # Update this to reference the correct path inside the container
      - FIREBASE_CREDENTIALS=/app/cybershieldai-firebase-adminsdk-fbsvc-36a8d0d55c.json
      - ALLOWED_HOSTS=*
      - CORS_ORIGINS=*

    volumes:
      - ./backend:/app 
      # Remove this line - the file is already in the backend directory which we're mounting as /app
      # - ./cybershieldai-firebase-adminsdk-fbsvc-36a8d0d55c.json:/app/cybershieldai-firebase-adminsdk-fbsvc-36a8d0d55c.json 
      - model-data:/app/models
    networks:
      - cybershield-network
    container_name: cybershield-backend

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - cybershield-network
    container_name: cybershield-mongodb
    environment:
      - MONGO_INITDB_DATABASE=cybershield_db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  cybershield-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local
  model-data:
    driver: local